### ISSUE TITLE
Scroll doesn't reset when switching the tabs while scrolled to top

### ISSUE THREAD

**Issue by chichkanov** [SwiftKickMobile/SwiftUIMaterialTabs#12] opened 2024-09-17 09:04 UTC
Steps to repro:
1. Create two tabs with a scrollable content
2. Scroll first tab content
3. Go to the second tab and scroll to top
4. Go back to the first tab

Issues:
1. I believe scroll should be reset. This is how it works in X and Instagram
2. If I scroll to top there is some janky header animation

Was testing the latest main branch

Sample
```
enum Tab: Hashable {
    case first
    case second
}

struct ContentView: View {
    
    @State var selectedTab: Tab = .first
    
    var body: some View {
        MaterialTabs(
            selectedTab: $selectedTab,
            headerTitle: { context in
                VStack {
                    Text("Material Tabs")
                        .font(.title)
                    
                    Text("Some long long description bla\nsecond line of text bla bla bal")
                        .font(.callout)
                        .foregroundStyle(.secondary)
                }
                .padding()
                .headerStyle(OffsetHeaderStyle(fade: true), context: context)
            },
            headerTabBar: { context in
                MaterialTabBar(selectedTab: $selectedTab, sizing: .equalWidth, context: context)
            },
            headerBackground: { context in
                Color.white
            },
            content: {
                firstTabContent()
                secondTabContent()
            }
        )
    }
    
    @ViewBuilder private func firstTabContent() -> some View {
        MaterialTabsScroll(tab: Tab.first) { _ in
            LazyVStack {
                ForEach(0..<100) { index in
                    Text("Row \(index)")
                        .padding()
                }
            }
        }
        .materialTabItem(tab: Tab.first, label: .secondary("First"))
    }
    
    @ViewBuilder private func secondTabContent() -> some View {
        MaterialTabsScroll(tab: Tab.second) { _ in
            LazyVStack {
                ForEach(0..<100) { index in
                    Text("Row \(index)")
                        .padding()
                }
            }
        }
        .materialTabItem(tab: Tab.second, label: .secondary("Second"))
    }
}
```

https://github.com/user-attachments/assets/93a4f39c-e21f-41a5-8dd4-c29c1f1b36cb

**Comment by wtmoose** [comment] 2024-09-17 15:17
Oof. Thanks for finding that. Seems this was a bug since iOS 17 that we never noticed. I'm looking into it

**Comment by wtmoose** [comment] 2024-09-17 18:41
This one should be fixed now if you'd like to take another look

**Comment by chichkanov** [comment] 2024-09-18 09:57
Hey @wtmoose . This doesn't seem to be fixed on the latest main branch


https://github.com/user-attachments/assets/e1a29f7f-8964-434a-8e71-e91498c4cebb

**Comment by wtmoose** [comment] 2024-09-18 14:29
@chichkanov the video you attached is behaving as designed and the header is not jumping as in the original video. Could you describe what behavior you're seeing vs what you expect?

From my perspective, when you return to the first tab, you're in an edge case where the header is full size but the scroll view is not at the top. From there, the header behavior depends on scroll direction:

1. When you scroll down (a.k.a. swipe up), the header shrinks—the header always shrinks when you scroll down.
2. When you scroll up (a.k.a. swipe down), the header maintains the current size until the top of the scroll view content meets the bottom of the header. If you continue to scroll up from there, the header expands.

**Comment by chichkanov** [comment] 2024-09-18 15:23
Hey! Sure, yeah. 

Here is a video which illustrated my expected behavior.

I think that whenever user started scrolling back and header becomes slightly visible, the scroll should be reset to zero on all tabs

https://github.com/user-attachments/assets/fdf7593f-d446-4d6e-8647-b3c0f9fe572e

**Comment by wtmoose** [comment] 2024-09-18 15:34
I've discussed with the team internally and we think the current behavior is ideal.

What you're showing in the above video is poor UX in my experience—user's don't want the app to automatically change their scroll position. If I scroll to something on Replies, the app should not reset that if I'm on another tab.

**Comment by chichkanov** [comment] 2024-09-18 15:38
> I've discussed with the team internally and we think the current behavior is ideal.
> 
> 
> 
> What you're showing in the above video is poor UX in my experience—user's don't want the app to automatically change their scroll position. If I scroll to something on Replies, the app should not reset that if I'm on another tab.

Interesting, I actually expect the opposite. But maybe because I use the apps where header can become pretty large, so it's gonna be a very bad UX if the scroll would've persisted when scrolled to top.
Do you have any example of the app which doesn't have this "poor UX"?

**Comment by wtmoose** [comment] 2024-09-18 16:08
If you think about a normal tabbed UI, such as the App Store app, each tab is logically independent from other tabs. I'm guessing that we would all agree, that scrolling on one tab would never affect scrolling on any other tab. The fact that we''re introducing an element outside of the tabs that can change size, doesn't fundamentally change the independence of the tabs. At least I can't think of a logical reason why it should.

If Android works as you're proposing (I don't have an Android device handy) or if this is common other iOS apps, I would say that this is a bad choice being propagated unless you can provide a compelling logical argument why the behavior is better.

**Comment by chichkanov** [comment] 2024-09-18 16:17
I didn't say that Android works this way. I am using iOS.

Instead of arguing, I'll just show you why all the social apps are not using the behavior you are suggesting. 
If you take a device smaller than 16 pro max, there won't be enough space to scroll.


https://github.com/user-attachments/assets/7fc07cba-76e9-47dc-8967-c4e7c25726d6

**Comment by chichkanov** [comment] 2024-09-18 16:19
> If you think about a normal tabbed UI, such as the App Store app, each tab is logically independent from other tabs. I'm guessing that we would all agree, that scrolling on one tab would never affect scrolling on any other tab. The fact that we''re introducing an element outside of the tabs that can change size, doesn't fundamentally change the independence of the tabs. At least I can't think of a logical reason why it should.
> 
> If Android works as you're proposing (I don't have an Android device handy) or if this is common other iOS apps, I would say that this is a bad choice being propagated unless you can provide a compelling logical argument why the behavior is better.

I didn't say Android works this way. I am using iOS and I am used to this experience. 

> If you think about a normal tabbed UI, such as the App Store app, each tab is logically independent from other tabs
I think this is a very wrong example since top tabs are very different from the TabBar

**Comment by chichkanov** [comment] 2024-09-18 16:21
> If Android works as you're proposing (I don't have an Android device handy) or if this is common other iOS apps, I would say that this is a bad choice being propagated unless you can provide a compelling logical argument why the behavior is better.


I didn't say Android works this way. I am using iOS and I am used to this experience. I got your point, sounds good


> If you think about a normal tabbed UI, such as the App Store app, each tab is logically independent from other tabs
 
I think this is a very wrong example since top tabs are very different from the TabBar

> At least I can't think of a logical reason why it should.

In my point of view if the user scrolled to the very top of the page, it's not an expected behavior to preserve the scroll position for all the other tabs

**Comment by wtmoose** [comment] 2024-09-18 16:37
I saw that you posted and deleted a response. That response had a valid counter-argument that you didn't include in your revised response.

Specifically, if the header is unusually tall, you can get in a situation where the user is stuck with a small scroll region. I'm going to label this ticket as an enhancement. I don't intend to change the default behavior, but I'm considering adding a configuration option.

If other people are reading this and disagree, chime in and make your case.

**Comment by chichkanov** [comment] 2024-09-18 16:54
> That response had a valid counter-argument that you didn't include in your revised response.

It's not a counter-argument. I deleted it because it wasn't making sense since if the header is too tall, user wouldn't be able to scroll properly in the first place.

**Comment by wtmoose** [comment] 2024-09-18 17:13
> It's not a counter-argument. I deleted it because it wasn't making sense since if the header is too tall, user wouldn't be able to scroll properly in the first place.

I'd say don't make headers so tall. But I do think it makes sense as a counter argument. In that scenario:

1. You __can__ freely scroll down (swipe up) because the header will shrink. Not a problem. Ideally, you could scroll by swiping in the header. However, SwiftUIMaterialTabs doesn't support this due to SwiftUI limitations. I can support this by dipping into UIKit (which I've tried to to avoid) so I added #16 for it.
2. You __can't__ freely scroll up (swipe down), because you're stuck scrolling in a small space. This is a legit problem if the header usually tall.

**Comment by wtmoose** [comment] 2024-09-19 19:03
OK this is implemented. I added a `MaterialTabsConfig` struct that you can optionally supply when constructing your `MaterialTabs`. I added two new behaviors and changed the default behavior. The behavior you requested is not the default, so you'll need to set `crossTabSyncMode = .resetScrollPosition`. If you want to take a look, I'm interested in your feedback.

````swift
public struct MaterialTabsConfig: Equatable {

    /// Specifies how the scroll view and header adjust to maintain continuity when switching tabs. These options affect one specific scenario. Suppose
    /// we have two tabs A and B and a collapsible title view:
    ///
    ///   1. User scrolls down (a.k.a swipes up) in tab A such that the title view is collapsed.
    ///   2. User switches to tab B and scrolls up (a.k.a swipes down) until the title view is expanded
    ///   3. User switches back to tab A
    ///
    /// Since the title view is expanded on tab A, but it would have naturally been collapsed, there are multiple strategies for how continuitity is preserved.
    public enum CrossTabSyncMode: Equatable {
        /// Preserves the scroll position relative to the header. If the header has moved up, the scroll view is moved up. If the header is moved down, the scroll
        /// view is moved down. The benefit of this approach is preserving the user's scroll position. The down side is that the header is expanded when it
        /// should be collapsed and will remain expanded if the user scrolls up, which could severely limit the space for scroll view content if the header
        /// is unusually tall.
        case preserveScrollPosition
        /// Resets the scroll position to align the top of the scroll view content is aligned with the bottom of the header. This is how many apps behave and
        /// it ensures that scroll position and title collapse state are always in sync. The down side is that the user's previous scroll position is lost.
        case resetScrollPosition
        /// Initially preserves the scroll position the same as `preserveContentOffset`. However, if the user scrolls, the title collapse state is
        /// animated to where match the scroll position. This option introduces a title view animation, but eliminates the down sides of other options.
        /// This is the default behavior.
        case resetTitleOnScroll(_ animation: Animation = .snappy(duration: 0.3))
    }

    public var crossTabSyncMode: CrossTabSyncMode = .resetTitleOnScroll()

    public init(crossTabSyncMode: CrossTabSyncMode = .resetTitleOnScroll()) {
        self.crossTabSyncMode = crossTabSyncMode
    }
}
````

**Closed as completed** 2024-09-22 22:05 UTC
Labels: enhancement

**Comment by wtmoose** [comment] 2024-09-22 22:07
2.0.3
